name: Generate ASCII
on: push

jobs:
  
  Generate-ASCII:

    runs-on: ubuntu-latest

    steps:
      - name: Message
        run: echo "This work flow is to generate ASCII"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Cowsay
        run: sudo apt-get install cowsay -y           #------ download cowsay library

      - name: Run cowsay cmd
        run: cowsay -f dragon "Run for corner, I am Dragon..........RAWR" >> dragon.txt

      - name: List & Read the file
        run: |
          ls -lrta
          cat dragon.txt